app = "tojan-bot"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  PYTHONUNBUFFERED = "1"
  MISE_PYTHON_COMPILE = "1"

[processes]
  app = "python finale.py"
