# fly.toml app configuration file generated for telegram-bot on 2025-09-05
# Documentation: https://fly.io/docs/reference/configuration/

app = "telegram-bot"   # change this to your actual Fly app name

primary_region = "iad" # or set to the region closest to you (e.g. "lhr", "fra", "sjc")

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  PYTHONUNBUFFERED = "1"
  MISE_PYTHON_COMPILE = "1"   # Fix for Python tarball extraction issue
  PORT = "8080"               # Required for Fly deployment

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1    # Keep at least one instance running
